version: '3.6'

services:
  api:
    build: .
    container_name: api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./data/static:/static
    networks:
      - api_network
  db:
    image: postgres
    restart: always
    env_file:
      - .env.db.dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api_network

networks:
  api_network:
    driver: bridge

volumes:
  postgres_data:
