"""update model task

Revision ID: dd1f2caca7b8
Revises: 5d290ee2b09c
Create Date: 2025-01-21 10:53:46.405275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1f2caca7b8'
down_revision = '5d290ee2b09c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'due_date')
    op.drop_column('task', 'start_date')
    op.drop_column('task', 'created_date')
    # ### end Alembic commands ###
